<?php
	# All available page types are described here.
	#
	# DO NOT EDIT THIS FILE
	#
	# However, if one is creating a new type, they should
	# add its description here too as this is the file
	# from which all depending on types functions read info
	# and so it affects which types would be shown in the
	# panel and would be deleted ACCORDINGLY
	
	# the following variables MUST NOT BE ALTERED in runtime
	
	# NOTE: DO NOT FORGET to update field `type` table `cm_struct_main` (as it is an emum)!
	
	#All type info
	$CM_PAGE_TYPES = array(
		'page' => array (
					'table' => 'cm_sp_pages',
					'caption' => 'страница',
					'description' => 'Страниците представляват блогове, които съдържат снимки, текст и линкове.',
					'files' => array('files', 'images') #no sub directories are allowed!
				),
		
		'image' => array (
					'table' => 'cm_sp_images',
					'caption' => 'снимка',
					'description' => 'Добавяйки снимки в дадена страница с включено "автоматично генериране на съдържанието", вие ефективно създавате фото-албум.',
					'files' => array()
				),
		
		'addon' => array(
					'table' => 'cm_sp_addons',
					'caption' => 'addon',
					'description' => 'Адоните са вътрешни страници изпълняващи специфичен код. Такива страници не се администрират в меню `Съдържание`, а в свое меню (ако въобще се администрират)',
					'files' => array('addon')
				),
		
		'link' => array(
					'table' => 'cm_sp_links',
					'caption' => 'връзка',
					'description' => 'Връзките позволяват външна информация да се вижда като част от сайта или да се препраща към нея',
					'files' => array() #No special dirs
				),
		
		'math' => array(
					'table' => 'cm_sp_math',
					'caption' => 'математика',
					'description' => 'Преформатиран математически текст. Съдържа множество (обикновено стотици) картинки, комбинирани в един спрайт (GIF+CSS), HTML текст и оригиналния текст (PDF, DOC, etc.)',
					'files' => array('attach_bg', 'attach_en', 'text_bg', 'text_en')
				)
	);
	
	# Names for iteration
	$CM_PAGE_TYPES_NAMES = array_keys($CM_PAGE_TYPES);
	
	# Tables for iteration
	$CM_PAGE_TYPES_TABLES = array();
	for ($i = 0; $i < count($CM_PAGE_TYPES_NAMES); $i++)
		$CM_PAGE_TYPES_TABLES[$i] = $CM_PAGE_TYPES[$CM_PAGE_TYPES_NAMES[$i]]['table'];
	# END
?>